# Porta do Servidor
server.port=8080

# --- CONFIGURAÇÃO PARA O BANCO DE DADOS SQLITE ---
spring.datasource.url=jdbc:sqlite:salut.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=br.com.salut.salutbackend.config.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Chave secreta para assinatura dos Tokens JWT (A LINHA QUE ESTAVA FALTANDO)
api.security.token.secret=minha-chave-secreta-super-segura-para-o-projeto-salut